#docker build -t postgres/relax:1.0 --rm=true .
#docker rm $(docker ps -a -q)
#MAINTAINER LIU "emaillf@163.com"

FROM ubuntu:16.04
#create directory
RUN mkdir -p /ruijie/relax
RUN mkdir -p /ruijie/git
RUN touch relax.log

#Download soft
RUN apt-get update && apt-get -y -q install git unzip wget
RUN git clone https://github.com/chinalf/chinalf.github.io.git /ruijie/git

#Install database
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update && apt-get -y -q install python-software-properties software-properties-common \
    && apt-get -y -q install postgresql-9.6 postgresql-client-9.6 postgresql-contrib-9.6

RUN cp /ruijie/git/docker_relax/tools/db/pg_partman.control /usr/share/postgresql/9.6/extension/pg_partman.control
RUN cp /ruijie/git/docker_relax/tools/db/pg_partman--2.4.1.sql /usr/share/postgresql/9.6/extension/pg_partman--2.4.1.sql
RUN chown postgres /ruijie/git/docker_relax/tools/db/dbinit.sql
RUN chown postgres /ruijie/git/docker_relax/tools/db/db.dump

USER postgres
RUN /etc/init.d/postgresql start \
    && psql -q -d postgres -f /ruijie/git/docker_relax/tools/db/dbinit.sql \
    && pg_restore -j4 -d itone /ruijie/git/docker_relax/tools/db/db.dump

RUN echo "local   all  postgres  peer" > /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "host all  all 127.0.0.1/32 trust" >> /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "host all  all  0.0.0.0/0  trust" >> /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.6/main/postgresql.conf
RUN mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql

#start db
USER root
CMD service postgresql start && tail -f relax.log

#Open ports
EXPOSE 5432

#clear
RUN apt-get -y autoremove git unzip wget && apt-get update
RUN rm -rf /ruijie/git
