FROM ubuntu:16.04

# 创建目录
RUN mkdir -p /ruijie/relax
RUN mkdir -p /ruijie/git

# 下载软件包
RUN apt-get update && apt-get -y -q install git unzip wget
RUN git clone http://docker:dockerrelax@172.17.189.70/relax/tools/docker/relax.git /ruijie/git

# 安装数据库
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update && apt-get -y -q install python-software-properties software-properties-common \
    && apt-get -y -q install postgresql-9.6 postgresql-client-9.6 postgresql-contrib-9.6

RUN cp /ruijie/git/tools/db/pg_partman.control /usr/share/postgresql/9.6/extension/pg_partman.control
RUN cp /ruijie/git/tools/db/pg_partman--2.4.1.sql /usr/share/postgresql/9.6/extension/pg_partman--2.4.1.sql
RUN chown postgres /ruijie/git/tools/db/dbinit.sql

USER postgres
RUN /etc/init.d/postgresql start \
    && psql -q -d itone -f /ruijie/git/tools/db/itone.sql
    && pg_restore -j4 -d itone db.dump

RUN echo "local   all  postgres  peer" > /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "host all  all 127.0.0.1/32 trust" >> /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "host all  all  0.0.0.0/0  trust" >> /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.6/main/postgresql.conf
RUN mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql

# 启动程序
CMD service postgresql start && /ruijie/relax/program/itone.sh && /bin/bash

# 开放端口
EXPOSE 5432
EXPOSE 9090

# 清除
RUN apt-get -y autoremove git unzip wget && apt-get update
RUN rm -rf /ruijie/git
